"""empty message

Revision ID: 1888349187ff
Revises: be8f34e39aeb
Create Date: 2020-06-30 19:36:53.140783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1888349187ff'
down_revision = 'be8f34e39aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herolo_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_herolo_users_name'), 'herolo_users', ['name'], unique=False)
    op.add_column('herolo_messages', sa.Column('message', sa.String(length=300), nullable=True))
    op.add_column('herolo_messages', sa.Column('reciever_id', sa.Integer(), nullable=True))
    op.add_column('herolo_messages', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('herolo_messages', sa.Column('subject', sa.String(length=300), nullable=True))
    op.create_foreign_key(None, 'herolo_messages', 'herolo_users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'herolo_messages', 'herolo_users', ['reciever_id'], ['id'], ondelete='SET NULL')
    op.drop_column('herolo_messages', 'chat_title')
    op.drop_column('herolo_messages', 'user_id')
    op.drop_column('herolo_messages', 'username')
    op.drop_column('herolo_messages', 'first_name')
    op.drop_column('herolo_messages', 'chat_id')
    op.drop_column('herolo_messages', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('herolo_messages', sa.Column('text', sa.VARCHAR(length=300), nullable=True))
    op.add_column('herolo_messages', sa.Column('chat_id', sa.INTEGER(), nullable=True))
    op.add_column('herolo_messages', sa.Column('first_name', sa.VARCHAR(length=240), nullable=True))
    op.add_column('herolo_messages', sa.Column('username', sa.VARCHAR(length=240), nullable=True))
    op.add_column('herolo_messages', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('herolo_messages', sa.Column('chat_title', sa.VARCHAR(length=240), nullable=True))
    op.drop_constraint(None, 'herolo_messages', type_='foreignkey')
    op.drop_constraint(None, 'herolo_messages', type_='foreignkey')
    op.drop_column('herolo_messages', 'subject')
    op.drop_column('herolo_messages', 'sender_id')
    op.drop_column('herolo_messages', 'reciever_id')
    op.drop_column('herolo_messages', 'message')
    op.drop_index(op.f('ix_herolo_users_name'), table_name='herolo_users')
    op.drop_table('herolo_users')
    # ### end Alembic commands ###
