"""empty message

Revision ID: 9292eb5aa16c
Revises: 2753aaa378b4
Create Date: 2019-04-15 09:19:56.265962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9292eb5aa16c'
down_revision = '2753aaa378b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('pic', sa.String(length=300), nullable=True))
    op.add_column('organisations', sa.Column('pic', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisations', 'pic')
    op.drop_column('entries', 'pic')
    # ### end Alembic commands ###
