"""empty message

Revision ID: c6211516e80e
Revises: a09a085b8d02
Create Date: 2020-07-01 10:15:24.538810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6211516e80e'
down_revision = 'a09a085b8d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('herolo_messages', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('herolo_messages', 'status')
    # ### end Alembic commands ###
