"""empty message

Revision ID: f8edd5739607
Revises: 1888349187ff
Create Date: 2020-07-01 03:09:36.654865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8edd5739607'
down_revision = '1888349187ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_messages')
    op.drop_table('organisations')
    op.drop_table('entries')
    op.create_foreign_key(None, 'herolo_messages', 'herolo_users', ['reciever_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'herolo_messages', 'herolo_users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.drop_column('herolo_messages', 'username')
    op.drop_column('herolo_messages', 'chat_id')
    op.drop_column('herolo_messages', 'chat_title')
    op.drop_column('herolo_messages', 'first_name')
    op.drop_column('herolo_messages', 'user_id')
    op.drop_column('herolo_messages', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('herolo_messages', sa.Column('text', sa.VARCHAR(length=300), nullable=True))
    op.add_column('herolo_messages', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('herolo_messages', sa.Column('first_name', sa.VARCHAR(length=240), nullable=True))
    op.add_column('herolo_messages', sa.Column('chat_title', sa.VARCHAR(length=240), nullable=True))
    op.add_column('herolo_messages', sa.Column('chat_id', sa.INTEGER(), nullable=True))
    op.add_column('herolo_messages', sa.Column('username', sa.VARCHAR(length=240), nullable=True))
    op.drop_constraint(None, 'herolo_messages', type_='foreignkey')
    op.drop_constraint(None, 'herolo_messages', type_='foreignkey')
    op.create_table('entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('address', sa.VARCHAR(length=240), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('org_id', sa.INTEGER(), nullable=True),
    sa.Column('pic', sa.VARCHAR(length=300), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('address', sa.VARCHAR(length=240), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pic', sa.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('telegram_messages',
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('chat_id', sa.INTEGER(), nullable=True),
    sa.Column('chat_title', sa.VARCHAR(length=240), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=240), nullable=True),
    sa.Column('username', sa.VARCHAR(length=240), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('text', sa.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###
