"""empty message

Revision ID: fa4f462d77a9
Revises: c6211516e80e
Create Date: 2020-07-03 00:52:11.158198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4f462d77a9'
down_revision = 'c6211516e80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_constraint(None, 'herolo_messages', type_='foreignkey')
    op.drop_constraint(None, 'herolo_messages', type_='foreignkey')
    op.add_column('herolo_users', sa.Column('privat_key', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('herolo_users', 'privat_key')
    op.create_foreign_key(None, 'herolo_messages', 'herolo_users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'herolo_messages', 'herolo_users', ['reciever_id'], ['id'], ondelete='SET NULL')
    op.drop_table('user')
    # ### end Alembic commands ###
